// H2 GSC SOURCE
// Decompiled by https://github.com/xensik/gsc-tool

initcredits_gflh2()
{
    maps\_credits::addcenterimage("H2_GFL_LOGO", 256, 128, 4.375);
    maps\_credits::addspace();

    maps\_credits::addcenterheading("Developers");
    maps\_credits::addgap();
    maps\_credits::addcentertriple("", "Loyalists", "");
    maps\_credits::addcentertriple("", "GEEKiDoS", "");
    maps\_credits::addcentertriple("", "k7Ysh5A_4.1.", "");
    maps\_credits::addgap();

    maps\_credits::addcenterheading( "Cast" );
    maps\_credits::addgap();
    maps\_credits::addcentertriple( "", "HK416", "" );
    maps\_credits::addcentertriple( "", "UMP45", "" );
    maps\_credits::addcentertriple( "", "UMP9", "" );
    maps\_credits::addcentertriple( "", "G11", "" );
    maps\_credits::addcentertriple( "", "M4A1", "" );
    maps\_credits::addcentertriple( "", "M4 SOPMOD II", "" );
    maps\_credits::addcentertriple( "", "RO635", "" );
    maps\_credits::addcentertriple( "", "ST AR-15", "" );
    maps\_credits::addcentertriple( "", "Suomi", "" );
    maps\_credits::addcentertriple( "", "Dima", "" );
    maps\_credits::addcentertriple( "", "Commander", "" );
    maps\_credits::addgap();

    maps\_credits::addcenterheading( "Additional Cast (dying all the time lol)" );
    maps\_credits::addgap();
    maps\_credits::addcenternamedouble( "P90", "9A-91" );
    maps\_credits::addcenternamedouble( "RFB", "Type-97" );
    maps\_credits::addcenternamedouble( "Saiga-12", "FNC" );
    maps\_credits::addcenternamedouble( "Sten MkII", "AK74M" );
    maps\_credits::addcenternamedouble( "SP9", "TAC-50" );
    maps\_credits::addcenternamedouble( "PPSh-41", "Super SASS" );
    maps\_credits::addcenternamedouble( "MP7", "M14" );
    maps\_credits::addcenternamedouble( "SV-98", "G36C" );
    maps\_credits::addcenternamedouble( "SPAS-12", "" );
    maps\_credits::addcenternamedouble( "Vespid", "Ripper" );
    maps\_credits::addcenternamedouble( "Jaeger", "Guard" );
    maps\_credits::addgap();

    maps\_credits::addcenterheading( "3D Artists" );
    maps\_credits::addgap();
    maps\_credits::addcentertriple( "", "Meru-San", "" );
    maps\_credits::addcentertriple( "", "nuv", "" );
    maps\_credits::addgap();

    maps\_credits::addcenterheading("Special Thanks");
    maps\_credits::addgap();
    maps\_credits::addcenternamedouble("fed", "Johnny");
    maps\_credits::addgap();
}

initiwcredits_iw()
{
    initcredits_gflh2();
    maps\_credits::addcenterimage( "LOGO_INFINITYWARD", 256, 128, 4.375 );
    maps\_credits::addspace();
    maps\_credits::addcenterheading( &"CREDIT_H2_ORIGINAL_TEAM" );
    maps\_credits::addgap();
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AARON_TRACY", &"CREDIT_H2_JORDAN_HIRSH" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ADAM_SCHMIDT", &"CREDIT_H2_JORDAN_MARDER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALAN_MEYERSON", &"CREDIT_H2_JOSH_GILMAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALESSANDRO_BARTOLUCCI", &"CREDIT_H2_JULIAN_LUD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEX_BRONQUETTE", &"CREDIT_H2_JUSTIN_HARRIS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEX_VEADOV", &"CREDIT_H2_JUSTIN_THEROUX" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXANDER_ROYCEWICZ", &"CREDIT_H2_KAI_WULFF" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDREW_KAWCZYNSKI", &"CREDIT_H2_KATIA_LEWIN_PALOMO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDREW_WANG", &"CREDIT_H2_KEITH_NED_BELL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDREW_ZACH", &"CREDIT_H2_KEITH_DAVID" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANNA_GRAVES", &"CREDIT_H2_KEVIN_MCKIDD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANTHONY_RUBIN", &"CREDIT_H2_KIRK_THORNTON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ATLI_ORVARSSON", &"CREDIT_H2_KRISTIN_COTTERELL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BARRY_PEPPER", &"CREDIT_H2_KRISTOF_KONRAD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BART_HENDRICKSON", &"CREDIT_H2_LANCE_HENRIKSEN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BILLY_MURRAY", &"CREDIT_H2_LEI_YANG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BOB_CALL_ME_OLD_FASHIONED_BADAMI", &"CREDIT_H2_LISA_STONE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BORIS_KIEVSKY", &"CREDIT_H2_LORNE_BALFE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRAD_ALLEN", &"CREDIT_H2_MACKEY_MCCANDLISH" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRENT_MCLEOD", &"CREDIT_H2_MARIO_PEREZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRIAN_BLOOM", &"CREDIT_H2_MARK_A_RUBIN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRUCE_FERRIZ", &"CREDIT_H2_MARK_GANUS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRYAN_KUHN", &"CREDIT_H2_MARK_GRIGSBY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BYRON_BEEDE", &"CREDIT_H2_MARK_MANCINA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CANDICE_CAPEN", &"CREDIT_H2_MARY_BENITEZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CARLY_GILLIS", &"CREDIT_H2_MATT_LINDQUIST" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CATHIE_ICHIGE", &"CREDIT_H2_MATT_MERCER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHAD_BARB", &"CREDIT_H2_MAURICIO_LANGE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHAD_GRENIER", &"CREDIT_H2_MICHAEL_A_BOON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHANCE_GLASCO", &"CREDIT_H2_MICHAEL_CUDLITZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHARLIE_WIEDERHOLD", &"CREDIT_H2_MICHAEL_PENROD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHELSY_BERRY", &"CREDIT_H2_MIKE_DENNY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHENG_LOR", &"CREDIT_H2_MIKE_MANTARRO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_LAI", &"CREDIT_H2_MIKE_SEAL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_LAMBERT", &"CREDIT_H2_MOHAMMAD_ALAVI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_SHEPHERD", &"CREDIT_H2_NATHAN_SILVERS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRISSY_ARYA", &"CREDIT_H2_NEEL_KAR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRISTOPHER_CHERUBINI", &"CREDIT_H2_NICK_PHOENIX" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRISTOPHER_DIONNE", &"CREDIT_H2_NOAH_SOROTA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CLAY_DUNCAN", &"CREDIT_H2_OSCAR_LOPEZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_COY_CLARK", &"CREDIT_H2_PAUL_MESSERLY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CRAIG_FAIRBRASS", &"CREDIT_H2_PAUL_SANDLER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CURTIS_JACKSON", &"CREDIT_H2_PETE_BLUMEL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAN_PINDER", &"CREDIT_H2_PETER_CHEN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DANIEL_GAMBURG", &"CREDIT_H2_PRESTON_GLENN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DANIEL_WAPNER", &"CREDIT_H2_RANDY_STONITSCH" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVE_MALLOW", &"CREDIT_H2_RAYME_C_VINSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVE_METZGER", &"CREDIT_H2_RICHARD_BAKER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_JOHNSON", &"CREDIT_H2_RICHARD_KRIEGLER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_LODGE", &"CREDIT_H2_RICHARD_N_SMITH" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DERRIC_EADY", &"CREDIT_H2_ROBERT_A_DYE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DREW_MCCOY", &"CREDIT_H2_ROBERT_BOWLING" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EARL_HAMMON_JR", &"CREDIT_H2_ROBERT_FIELD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ED_HARMER", &"CREDIT_H2_ROBERT_GAINES" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ENAYAT_DELAWARY", &"CREDIT_H2_ROGER_ABRAHAMSSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ERIC_PIERCE", &"CREDIT_H2_ROMAN_VARSHAVSKY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EUGENE_ALPERS", &"CREDIT_H2_RYAN_M_LASTIMOSA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EUGENE_LAZAREB", &"CREDIT_H2_RYELAND_ALLISON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FRANCESCO_GIGLIOTTI", &"CREDIT_H2_SAM_SAKD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FRED_TATASCIORE", &"CREDIT_H2_SAMI_ONUR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FRED_TOMA", &"CREDIT_H2_SATHAM_RAMGOTRA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GABRIELLE_ALRAJHI", &"CREDIT_H2_SEAN_SLAYBACK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GEOFFREY_SMITH", &"CREDIT_H2_SEROZH_SARKISYAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GEORGENINA_SCHALLER", &"CREDIT_H2_SIMON_COURNOYER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GLENN_MORSHOWER", &"CREDIT_H2_SLAMM_ANDREWS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GRAHAM_MCTAVISH", &"CREDIT_H2_STEPHEN_MILLER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HANS_ZIMMER", &"CREDIT_H2_STEVE_FUKUDA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JACOB_SHEA", &"CREDIT_H2_STEVEN_GIESLER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAKE_KEATING", &"CREDIT_H2_STEVEN_KOFSKY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JANICE_LOHR_TURNER", &"CREDIT_H2_SVEN_HOLMBERG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JASON_MCCORD", &"CREDIT_H2_TAEHOON_OH" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JASON_WEST", &"CREDIT_H2_TERRAN_CASEY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEFF_BIGGERS", &"CREDIT_H2_THEERAPOL_SRISUPHAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEFF_HEATH", &"CREDIT_H2_THOMAS_BERGERSEN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JESSE_STERN", &"CREDIT_H2_TIM_MCGRATH" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JIESANG_SONG", &"CREDIT_H2_TODD_ALDERMAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JIM_WARD", &"CREDIT_H2_TODD_SUE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOEL_EMSLIE", &"CREDIT_H2_TOM_BRODERICK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOEL_GOMPERT", &"CREDIT_H2_TROY_BAKER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOHN_HAGGERTY", &"CREDIT_H2_VELINDA_PELAYO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOHN_THEODORE", &"CREDIT_H2_VINCE_ZAMPELLA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOHN_WASILCZYK", &"CREDIT_H2_WILL_ARNETT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JON_DAVIS", &"CREDIT_H2_WILLIAM_CHO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JON_PORTER", &"CREDIT_H2_ZACH_VOLKER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JON_SHIRING", &"CREDIT_H2_ZIED_RIEKE" );
    maps\_credits::addgap();
}

initiwcredits_beenox()
{
    maps\_credits::addcenterimage( "LOGO_BEENOX", 256, 128, 4.375 );
    maps\_credits::addgap();
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ADAM_BLANCHETMAINVILLE", &"CREDIT_H2_JONATHAN_GOSSELIN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ADAM_ROSENHEK", &"CREDIT_H2_JONATHAN_RANCOURT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ADHAM_EL_KOSHT", &"CREDIT_H2_JONATHAN_STANDRE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ADRIEN_LELIEVRE", &"CREDIT_H2_JULIEN_ALLARD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALAIN_BELLEHUMEUR", &"CREDIT_H2_JULIEN_BARRET" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALAIN_LAUZE", &"CREDIT_H2_KAREN_POULIN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEC_THIBAULT", &"CREDIT_H2_KARIM_IDRISSI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXANDR_VOROBYEV", &"CREDIT_H2_KARINE_MALLET" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXANDRE_BERGERON", &"CREDIT_H2_KARINE_WINDY_BOUDREAULT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXANDRE_BLANCHETDESLOGES", &"CREDIT_H2_KASSANDRA_WILLIAMSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXANDRE_COSSETTE", &"CREDIT_H2_KEVEN_FORTIN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXANDRE_LESSARD", &"CREDIT_H2_KEVEN_LANDRYCANTIN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDREANNE_DION_LANDRY", &"CREDIT_H2_KEVIN_ROYER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANTHONY_CARMONA", &"CREDIT_H2_KEVIN_VALLEE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANTONY_BOUDREAU", &"CREDIT_H2_LAURIANE_BERTRANDCHARETTE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ARNAUD_SIMONLAFOREST", &"CREDIT_H2_LAURIE_LESPERANCE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ASHISH_PARASHAR", &"CREDIT_H2_LOUISEMMANUEL_POTHIER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BAPTISTE_SIMAR", &"CREDIT_H2_LUCANDRE_MURRAY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BENOIT_RIVARD", &"CREDIT_H2_MARCALEXANDRE_MARCASBAKERS_BOULANGERMILOT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BERNARD_LANGLOIS", &"CREDIT_H2_MARCANDRE_MAD_DUCHARME" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BERTRAND_REMONDIN", &"CREDIT_H2_MARCANDRE_GAGNE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CAROLANE_LAKATOS", &"CREDIT_H2_MARCANTOINE_SAINDON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CATHERINE_BLOUIN", &"CREDIT_H2_MARIEELLA_PINSONNEAULT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CATHERINE_SIMARD", &"CREDIT_H2_MARIEEVE_TREMBLAY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHARLESETIENNE_DESBIENS", &"CREDIT_H2_MARIEJOELLE_GINGRAS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_BRUIN", &"CREDIT_H2_MARIELLE_DIONROBIDOUX" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CINDY_VILLENEUVE", &"CREDIT_H2_MARIEPIER_DESMARAIS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CORENTIN_SIBRET", &"CREDIT_H2_MARIO_ALMAGUER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CYNTHIA_VANDERMOUTEN", &"CREDIT_H2_MARIO_NOTARO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAMIEN_DOZIAS", &"CREDIT_H2_MATHIEU_BIBEAUMORIN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DANIEL_DEMERS", &"CREDIT_H2_MATHIEU_BROUILLETTE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DANNY_ANGELO_CARMINATI_GREIN", &"CREDIT_H2_MATHIEU_DENIS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVE_BERGERON", &"CREDIT_H2_MATHIEU_GOSSELIN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_BLONDEAU", &"CREDIT_H2_MATHIEU_GRIGNONROY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_BOURDAGES", &"CREDIT_H2_MATHIEU_HUNTER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_COLINDOIRON", &"CREDIT_H2_MATHIEU_MERCIER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_LALANCETTE", &"CREDIT_H2_MATTHEW_HARRIS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DELPHINE_AUBRY", &"CREDIT_H2_MAXIME_CARRIER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DOMINIC_CHARRON", &"CREDIT_H2_MAXIME_MONTCALM" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DOMINIC_MORIN", &"CREDIT_H2_MAXIME_PARADIS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DOMINIC_OUELLET", &"CREDIT_H2_MAXIME_PROULX" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DOMINIC_SIMARD", &"CREDIT_H2_MELANIE_SIMARD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DOMINIQUE_MAHE", &"CREDIT_H2_MICHAEL_BISSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DONATIEN_RABILLER", &"CREDIT_H2_MITCH_FOURNIER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EDOUARD_DIAMANTROBERT", &"CREDIT_H2_NATHAN_MORASSE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ERIC_GIRARD", &"CREDIT_H2_NICOLAS_STPIERRE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ERIC_LAVOIE", &"CREDIT_H2_NICOLAS_TREMBLAY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ERIC_BOB_POULIOT", &"CREDIT_H2_NOUR_POLLONI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ETIENNE_BEAULIEU", &"CREDIT_H2_OLIVIER_BELLETETE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ETIENNE_BLONDEAU", &"CREDIT_H2_OLIVIER_DUPONT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ETIENNE_GIGUERE", &"CREDIT_H2_OLIVIER_GAGNEHOULE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ETIENNE_FREDPOP_POULIOT", &"CREDIT_H2_OPHELIE_PELLOUXPRAYER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EVE_MAINGUY", &"CREDIT_H2_PASCAL_BRULOTTE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EVERTON_FERNANDO_PATITUCCI_DA_SILVA", &"CREDIT_H2_PATRICK_BOULANGER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FELIX_LALIBERTE", &"CREDIT_H2_PATRICK_RENAUD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FELIXANTOINE_DESYGILLIES", &"CREDIT_H2_PHILIPPE_STARNAUD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FRANCIS_LAGRANGE", &"CREDIT_H2_PHILIPPE_TROIE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FRANCOIS_DURAND", &"CREDIT_H2_PHILIPPE_TURCOTTE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FRANCOIS_GRATTON", &"CREDIT_H2_PHILIPPE_VALOIS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FRANCOIS_HAMEL", &"CREDIT_H2_PIERREDANTE_DELBOULLE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FRANCOIS_TADDEI", &"CREDIT_H2_PIERRELUC_CORMIER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FREDERIC_FORTIN", &"CREDIT_H2_PIERRELUC_GRONDINES" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FREDERIC_WILSON", &"CREDIT_H2_RAPHAEL_CORBIN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FREDERICK_IMBEAULT", &"CREDIT_H2_RAPHAEL_GUAYPICARD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GABRIEL_BOUFFARD", &"CREDIT_H2_REMI_EDMOND" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GABRIEL_DION", &"CREDIT_H2_RICHARD_DUBREUIL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GABRIEL_NADEAU", &"CREDIT_H2_RICHARD_HARVEYLEVERT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GABRIEL_VEZINA", &"CREDIT_H2_ROBERT_SIMARD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GILBERT_SAMSON", &"CREDIT_H2_ROMAIN_LAVIGNE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GLEN_MARTIN", &"CREDIT_H2_SACHA_MEUNIER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GUILLAUME_ALAIN", &"CREDIT_H2_SAMUEL_CARRIER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GUILLAUME_AUBE", &"CREDIT_H2_SAMUEL_DUBOIS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GUILLAUME_AUDET", &"CREDIT_H2_SAMUEL_FRADETTE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GUILLAUME_G3_GAGNEGAUTHIER", &"CREDIT_H2_SAMUEL_GAUTHIER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GUILLAUME_G2_GAUTHIER", &"CREDIT_H2_SAMUEL_WHITTOM" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GUILLAUME_GOUDREAULT", &"CREDIT_H2_SEBASTIEN_GIROUX" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GUILLAUME_MORIN", &"CREDIT_H2_SEBASTIEN_GREGOIRE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HUBERT_DIAMANT", &"CREDIT_H2_SEBASTIEN_OUELLET" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_IAN_LEVESQUEPERREAULT", &"CREDIT_H2_SEBASTIEN_ROY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_IRVIN_THOMAS", &"CREDIT_H2_SIMON_CAUXBARGE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEANBENOIT_LACHANCE", &"CREDIT_H2_SIMON_CHARTIER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEANCHRISTOPHE_MARTIN", &"CREDIT_H2_SIMON_COUTURE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEANFRANCOIS_TREMBLAY", &"CREDIT_H2_SIMON_DOMPIERRE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEANPHILIPPE_ROSS", &"CREDIT_H2_SIMON_TREMBLAYGAUTHIER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEANPIERRE_LAPOINTE", &"CREDIT_H2_STEPHANE_BOURQUE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEANREMY_HORTH", &"CREDIT_H2_STEPHANE_GRAVEL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEREMY_DELWARTE", &"CREDIT_H2_STEPHANIE_LAPOINTE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEREMY_STAMANT", &"CREDIT_H2_STEVE_ROACH" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEREMY_THIBEAULT", &"CREDIT_H2_SYLVAIN_MOREL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEROME_WAUTHY", &"CREDIT_H2_TARIQ_BELLAOUI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JESSICA_CHENG", &"CREDIT_H2_THOMAS_RIGAUD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JESSY_JANE_BACON", &"CREDIT_H2_THOMAS_WILSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JIM_LEPAGE", &"CREDIT_H2_VINCENT_AUGER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JIMMY_LABERGE", &"CREDIT_H2_VINCENT_BEAUREGARD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JIMMY_SAMSON", &"CREDIT_H2_VINCENT_HEBERT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JIMMY_TAURU", &"CREDIT_H2_VINCENT_PAGEAU" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOEY_DESROSIERS", &"CREDIT_H2_WILLIAM_PAREJOBIN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOHANN_RIEDL", &"CREDIT_H2_WILLIAM_WELLEY_PARENTLABONTE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JONATHAN_BONIN", &"CREDIT_H2_YANNICK_FLEURIT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JONATHAN_COOK", &"CREDIT_H2_ZIKRIA_AMIRI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JONATHAN_FOURNIER", "" );
    maps\_credits::addgap();
    maps\_credits::addcenterheading( &"CREDIT_H2_BEENOX_SPECIAL_THANKS" );
    maps\_credits::addgap();
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXANDRA_BEAULIEU", &"CREDIT_H2_JEANFRANCOIS_BROWN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXANDRE_FONTAINEFERRON", &"CREDIT_H2_JEANFRANCOIS_FALARDEAU" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXANDRE_GRATTON", &"CREDIT_H2_JEANFRANCOIS_NADEAU" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BENJAMIN_DESCAMPS", &"CREDIT_H2_JESSICA_MOREAUROBERGE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BENJAMINPIER_DUMAS", &"CREDIT_H2_JULIE_ANNE_PAIEMENT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BENOIT_DUBREUIL", &"CREDIT_H2_JULIEN_BECIROVSKI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRIAN_FAGNANT", &"CREDIT_H2_KATIE_BOULET" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CASSIANO_FONTENELE_DE_CARVALHO_ROCHA", &"CREDIT_H2_LUC_FERLAND" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHARLES_DUFOUR", &"CREDIT_H2_MANUELLA_COULOMBE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRISTIAN_AUGERMORIN", &"CREDIT_H2_MARCANTOINE_JOLY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CLAUDE_LACHANCE", &"CREDIT_H2_MARIANE_VINCENT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DANIEL_BEAUDRY", &"CREDIT_H2_MARTIN_DUBE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_FORTIN", &"CREDIT_H2_MAXIME_CORRIVEAUTRUDEL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DOMINIC_POIRIER", &"CREDIT_H2_MAXIME_TURCOTTE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EMILIE_LAFLEUR", &"CREDIT_H2_MICHAEL_GUIMONT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ERIC_BERNARD", &"CREDIT_H2_NICHOLAS_LOSIER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FREDERIQUE_ARSENAULTCOTE", &"CREDIT_H2_PATRICK_COTE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GABRIEL_LAPOINTE", &"CREDIT_H2_PATRICK_DESBIENSWRIGHT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GENEVIEVE_JACQUES", &"CREDIT_H2_PAULINE_FROT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GUYLAINE_BOURQUE", &"CREDIT_H2_THALIAANN_COTEORTIZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ISABELLE_LACASSE", &"CREDIT_H2_VINCENT_RIBOU" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEANDAVID_PROULXMARCOUX", "" );
    maps\_credits::addspace();
    maps\_credits::addcentertriple( "", &"CREDIT_H2_FORCES_ARMEES_CANADIENNES__CANADIAN_ARMED_FORCES", "" );
    maps\_credits::addgap();
    maps\_credits::addcenterheading( &"CREDIT_H2_BEENOX_PRODUCTION_BABIES" );
    maps\_credits::addgap();
    maps\_credits::addcenternamedouble( &"CREDIT_H2_MARGOT_AUBE", &"CREDIT_H2_EDGAR_LAGRANGE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_SEAN_BISSON", &"CREDIT_H2_ELENA_LAGRANGE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ISAAC_BOULANGER", &"CREDIT_H2_EZEKIEL_ELLIOTT_ROSENHEK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHARLOTTE_HEBERT", &"CREDIT_H2_MARIUS_SAMSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EVAN_LABERGE", "" );
    maps\_credits::addgap();
}

initiwcredits_ca()
{
    maps\_credits::addcenterimage( "LOGO_CERTAINAFFINITY", 256, 128, 4.375 );
    maps\_credits::addgap();
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEKSEY_SPIVAK", &"CREDIT_H2_LAYNE_JOHNSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEX_CHRISMAN", &"CREDIT_H2_LEO_GONZALEZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEX_TEEBAGY", &"CREDIT_H2_LINCOLN_LI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDREW_MORRIS", &"CREDIT_H2_LORRAINE_ZAWADA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ARTHUR_CANAL", &"CREDIT_H2_MARK_ANDERSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ELISABETH_BEINKESCHWARTZ", &"CREDIT_H2_MARK_FLETCHER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BILL_CAMPBELL", &"CREDIT_H2_MARTIN_CABLE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRIAN_HUDSON", &"CREDIT_H2_MATT_DEMARAY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRYAN_MOSS", &"CREDIT_H2_MATTHEW_MCCREADY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BYRON_WELCH", &"CREDIT_H2_MATT_OZTALAY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CARLA_HAMILTON", &"CREDIT_H2_MATT_SOELL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHARLIE_WIEDERHOLD", &"CREDIT_H2_MAX_HOBERMAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DALE_HOMBURG", &"CREDIT_H2_MEGAN_MELENDI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_MERTZ", &"CREDIT_H2_MIKE_CLOPPER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_MIDGLEY", &"CREDIT_H2_MIKE_SLEGEIR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DEAN_MCCALL", &"CREDIT_H2_MOJDEH_GHARBI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DENNIS_PORTER", &"CREDIT_H2_NATHAN_MATES" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DEVIN_FLORA", &"CREDIT_H2_WIMOLRAT_TANGTIPHONGKUL_NIKKI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EDWARD_LYTTON", &"CREDIT_H2_OGNIAN_BONEV" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ERIC_MILLER", &"CREDIT_H2_PATRICK_BERGMAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FRANCESA_CASTELLANOS", &"CREDIT_H2_PHIL_WATTENBARGER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GARY_BERGERON", &"CREDIT_H2_RAMOND_TORRES" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GEOFF_TAYLOR", &"CREDIT_H2_RAY_ARRIAGA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GEOFF_YETTER", &"CREDIT_H2_RICHARD_SMITH" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HENRY_YU", &"CREDIT_H2_RICK_KNOX" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HYUNG_KIM", &"CREDIT_H2_RYAN_DAJO_FOX" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_IAN_VILLAMIN", &"CREDIT_H2_RYAN_MANSFIELD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAMES_WAHLQUIST", &"CREDIT_H2_RYAN_RUDE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAMES_WRENCH", &"CREDIT_H2_RYAN_TREADWELL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAN_HENDRIK_URSCHEL", &"CREDIT_H2_SAMUEL_INMAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JASON_BORNE", &"CREDIT_H2_SCOTT_DOWNEY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JASON_BRETZ", &"CREDIT_H2_SCOTT_LEPANEN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JASON_HUTCHINS", &"CREDIT_H2_SCOTT_STEVENS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JENNIFER_CASINADER", &"CREDIT_H2_SEOKI_KI_KWON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JENNIPHER_JUDGE", &"CREDIT_H2_SEOKIN_CHUNG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOHN_GRUBNER", &"CREDIT_H2_SISI_CASTRO_KRUEL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOHN_STAMOS", &"CREDIT_H2_STEVE_YOUNG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOHN_ZAGORSKI", &"CREDIT_H2_SUSAN_BOLLINGER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_KIERSTEN_SAMWELL", &"CREDIT_H2_THOMAS_WHITLOW" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_KYLE_UBERMAN", "" );
    maps\_credits::addgap();
}

initiwcredits_nerve()
{
    maps\_credits::addcenterimage( "LOGO_NERVE", 256, 128, 4.375 );
    maps\_credits::addgap();
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AARON_HAUSMANN", &"CREDIT_H2_JAMES_GRESKO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALAN_FLORES", &"CREDIT_H2_MICHAEL_INNIS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRYAN_CAVETT", &"CREDIT_H2_NICHOLAS_CLARK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_EDMISTON", &"CREDIT_H2_NOE_SERRANO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EDWARD_FERGUSON", &"CREDIT_H2_PHIL_WOHR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ETHAN_MCCAUGHEY", &"CREDIT_H2_TIM_LEWIS" );
    maps\_credits::addgap();
}

initiwcredits_irongalaxy()
{
    maps\_credits::addcenterimage( "LOGO_IRONGALAXY", 256, 128, 4.375 );
    maps\_credits::addgap();
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXANDER_STOPAR", &"CREDIT_H2_JOSH_MELNICK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDREW_MASSARI", &"CREDIT_H2_JUSTIN_AUGSPURGER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAN_COLEMAN", &"CREDIT_H2_MARIO_GOMEZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DARRYL_WISNER", &"CREDIT_H2_MATT_SECRIST" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JONATHAN_VONGKORAD", &"CREDIT_H2_NATHAN_MEFFORD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOSH_CRIZ", "" );
    maps\_credits::addgap();
}

_id_C851()
{
    maps\_credits::_id_BB08( "LOGO_ACTIVISION", 256, 128, 3.875 );
    maps\_credits::addgap();
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AARON_BRINKMAN", &"CREDIT_H2_JONATHAN_OSORIO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AARON_CASTELLAN", &"CREDIT_H2_JONATHAN_PAETZOLD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AARON_CHAMBERS", &"CREDIT_H2_JORDAN_CAMERON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AARON_KAPKE", &"CREDIT_H2_JORDAN_STARMER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AARON_ROSEMAN", &"CREDIT_H2_JORGE_PONCE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AARON_SEEDS", &"CREDIT_H2_JOSEPH_ARANDA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ABBY_ALBRIGHT", &"CREDIT_H2_JOSEPH_CAMMORATA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ABE_WELLUMSON", &"CREDIT_H2_JOSEPH_LAPAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ABRAHAM_BROUWER", &"CREDIT_H2_JOSEPH_MATHESON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ADAM_DUBOIS", &"CREDIT_H2_JOSEPHINE_DAM" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ADAM_FOSHKO", &"CREDIT_H2_JOSH_BRIDGE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ADAM_PHILLIPS", &"CREDIT_H2_JOSH_HARBO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ADAM_ZUCKER", &"CREDIT_H2_JOSH_NEGRIN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ADELA_VANG", &"CREDIT_H2_JOSH_SWENSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ADRIAN_DEVALLY", &"CREDIT_H2_JOSH_TAUB" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AFZAL_SHAIK", &"CREDIT_H2_JOSH_WIELENGA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AIMU_KIKUCHI", &"CREDIT_H2_JOSHUA_BOROWICK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AJITH_KUMAR", &"CREDIT_H2_JOSHUA_SELINGER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AKHIL_GUPTA", &"CREDIT_H2_JOSHUA_TAUB" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AL_CALVANICO", &"CREDIT_H2_JOXEAN_KORET" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALAA_ALRAMLY", &"CREDIT_H2_JOYCE_CHANG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALADDIN_SUQI", &"CREDIT_H2_JUDY_HO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALAN_VALLE", &"CREDIT_H2_JULIA_KAZAKS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALAN_WIESSBROD", &"CREDIT_H2_JULIAN_CALLY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALANA_SHERER", &"CREDIT_H2_JULIAN_DE_LOS_PRADOS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALBERTO_CORREA_TOSTICROCE", &"CREDIT_H2_JUSTIN_MCFARLAND" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALDEN_PAGUIA", &"CREDIT_H2_JUSTIN_REYNOLDS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEJANDRO_ARREOLA", &"CREDIT_H2_JUSTIN_TAYLOR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEKSANDRS_FIRJANS", &"CREDIT_H2_JUSTIN_WOOD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEX_BROWN", &"CREDIT_H2_KAI_HSU" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEX_DEL_CAMPO", &"CREDIT_H2_KALA_SUBRAMANIAM" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEX_HARTUNG", &"CREDIT_H2_KALISSA_REINS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEX_MARQUEZ", &"CREDIT_H2_KAP_KANG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEX_REICHMAN", &"CREDIT_H2_KAREN_SEGAWA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEX_SCHINDELDECKER", &"CREDIT_H2_KAREN_STARR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEX_SMITH", &"CREDIT_H2_KARI_HISCOX" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXANDER_BROWN", &"CREDIT_H2_KATE_OGOSTA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXANDER_SPRY", &"CREDIT_H2_KATIE_CHENG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXANDRA_CROELL", &"CREDIT_H2_KATY_ANDREWS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXIS_DEMURGER", &"CREDIT_H2_KAYLA_DICKEY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXIS_LOPEZ", &"CREDIT_H2_KECIA_CHRISTIANSEN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALFIO_FEDERICO_DI_PINTO", &"CREDIT_H2_KEITH_COX" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALI_TIRMIZI", &"CREDIT_H2_KEITH_HAMMONS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALICE_HINES", &"CREDIT_H2_KELVIN_MATSUMOTO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALLEN_CORONA", &"CREDIT_H2_KENNETH_CURTIS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALLISON_MERAZ", &"CREDIT_H2_KENNETH_OFARRELL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALPTEKIN_OZAY", &"CREDIT_H2_KENNETH_TANAKA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AMAANI_SHAMS", &"CREDIT_H2_KENNY_IVERSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AMANDA_OKEEFFE", &"CREDIT_H2_KEVIN_CHANG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AMBER_HOLMES", &"CREDIT_H2_KEVIN_CHESTER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AMIT_SHRIVASTAVA", &"CREDIT_H2_KEVIN_FLYNN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AMY_LONGHI", &"CREDIT_H2_KEVIN_FRYERS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANADEGE_DOSSANTOSFREITAS", &"CREDIT_H2_KEVIN_HAAS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANADEGE_SANTOS", &"CREDIT_H2_KEVIN_HENDRICKSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANAMARIA_WEILAND", &"CREDIT_H2_KEVIN_PETERSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDER_NICKELL", &"CREDIT_H2_KHALID_ASHER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDRE_LOPEZ", &"CREDIT_H2_KHALID_KHWAJA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDREA_NIEMAN_DEHART", &"CREDIT_H2_KIM_KOSSACK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDREW_BEZER", &"CREDIT_H2_KIMBERLY_CARRASCO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDREW_CHAPMAN", &"CREDIT_H2_KIMBERLY_VOXLAND" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDREW_ELLIOTT", &"CREDIT_H2_KORI_OROZCO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDREW_HOFFACKER", &"CREDIT_H2_KRISTI_BASO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDREW_IRVIN", &"CREDIT_H2_KRISTIAN_CROELL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDY_BEZER", &"CREDIT_H2_KRISTINA_WONG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDY_COOK", &"CREDIT_H2_KRZYSZTOF_SAGOLA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDY_HENDRICKSON", &"CREDIT_H2_KUIYING_MENG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDY_NGUYEN", &"CREDIT_H2_KUMARAVEL_PONNUSAMY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANGELA_PARK", &"CREDIT_H2_KYLE_BERGMAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANGELO_PESCE", &"CREDIT_H2_KYLE_CARRANZA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANN_GREALY", &"CREDIT_H2_KYLE_DIEKER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANTHONINO_RIONDA", &"CREDIT_H2_KYLE_KLEVEN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANTONIA_SLAPAC", &"CREDIT_H2_KYLE_MOTT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ARIANA_JEZ", &"CREDIT_H2_KYLE_OWEN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ARIEL_GONZALEZ", &"CREDIT_H2_KYLE_WALKER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ASHLEY_KELLY", &"CREDIT_H2_KYOUNGHWA_PARK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ASHLEY_MAIDY", &"CREDIT_H2_LAETITIA_MEJASSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ASHOK_RAMADOSS", &"CREDIT_H2_LAURA_LUCAS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AUSTIN_RUNNING", &"CREDIT_H2_LAURA_SIFFERLE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AUSTIN_SMYTHE", &"CREDIT_H2_LAURENCE_SNOW" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BALJINDER_SINGH", &"CREDIT_H2_LEE_GODFREY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BAO_CALVIN_VU", &"CREDIT_H2_LEIGH_SEBBY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BARIS_SEKER", &"CREDIT_H2_LESLIE_SOTO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BARRY_KEHOE", &"CREDIT_H2_LETICIA_SESSA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BARTOSZ_ROGALA", &"CREDIT_H2_LINDSAY_FRIEDMAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BARUD_TESFAYE", &"CREDIT_H2_LINDSAY_MURPHY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BECKY_CZAICKA", &"CREDIT_H2_LINDSAY_PAI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BEN_BRUNS", &"CREDIT_H2_LISA_COBELLO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BEN_PERRY", &"CREDIT_H2_LOGAN_HOLLIDAY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BEN_SYLVESTER", &"CREDIT_H2_LOGAN_ROGERS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BENJAMIN_PIRKEY", &"CREDIT_H2_LOIC_OLICHON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BERTRAND_LEROUX", &"CREDIT_H2_LONNIE_CHATMAN_JR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BILL_VAUGHAN", &"CREDIT_H2_LOUIS_BLACKWELL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BOB_AU", &"CREDIT_H2_LUCIO_TADEU_TORELLI_VIANNA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BOB_LOYA", &"CREDIT_H2_LUIS_ARNIELLAVEGA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BOB_WHARTON", &"CREDIT_H2_LUIS_FLORES_CASAS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BOBBY_KOTICK", &"CREDIT_H2_LUKE_MACKAY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BOOTH_RAMSAY", &"CREDIT_H2_LYDIA_LI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRAD_MANDAS", &"CREDIT_H2_LYNN_BALLEW" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRAD_SAAVEDRA", &"CREDIT_H2_MAHESH_TYAGI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRANDON_CEDERHOLM", &"CREDIT_H2_MAI_MIYAKAWA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRANDON_HELT", &"CREDIT_H2_MAILE_ROBERTSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRANDON_MERILLAT", &"CREDIT_H2_MAISHA_CARTER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRANDON_RUSS", &"CREDIT_H2_MAISOUN_QUASEM" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRANDON_SCHEBLER", &"CREDIT_H2_MALIK_JIFFRY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRANDON_ZIEN", &"CREDIT_H2_MANNIX_KELLY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRANDT_SNYDER", &"CREDIT_H2_MANUEL_BRONNER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRETT_BROWN", &"CREDIT_H2_MANUELA_LORITZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRIAN_BENNETT", &"CREDIT_H2_MARC_YAMMINE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRIAN_BENSI", &"CREDIT_H2_MARCELLO_VIDES" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRIAN_BOGDAN", &"CREDIT_H2_MARCELO_TERACINI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRIAN_CASTLE", &"CREDIT_H2_MARCUS_STOLL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRIAN_DEWOLF", &"CREDIT_H2_MARCUS_TOON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRIAN_EHRICH", &"CREDIT_H2_MARIA_EUGENIA_COPPOLA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRIAN_MONSON", &"CREDIT_H2_MARIA_SIMKHES" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRIAN_SHANAHAN", &"CREDIT_H2_MARIA_YANEZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRIAN_STOLZ", &"CREDIT_H2_MARIE_BAGNELL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRIAN_STRUMPF", &"CREDIT_H2_MARIO_SGAMBELLURI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRITTANY_LANSING", &"CREDIT_H2_MARISA_MUSCARI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRUNO_CORDEIRO", &"CREDIT_H2_MARK_HAMLON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BRYAN_UMANA", &"CREDIT_H2_MARK_MATTHEWS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BYRON_BEEDE", &"CREDIT_H2_MARQUIS_CANNON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CAMERON_CHAPMAN", &"CREDIT_H2_MARVIN_IGNACIO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CAMERON_DOW", &"CREDIT_H2_MARVIN_JACOME" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CAMERON_JOHNSTONE", &"CREDIT_H2_MARVIN_SUPAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CAMERON_PETERSON", &"CREDIT_H2_MATT_COX" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CARL_HUGHES", &"CREDIT_H2_MATT_GRAHN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CARL_LEHMANN", &"CREDIT_H2_MATT_IRSFELD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CARLOS_AVILES_ORR", &"CREDIT_H2_MATT_PISCITELLO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CARLOS_EDUARDO_PAGANO_COLATO", &"CREDIT_H2_MATTHEW_BLYSTONE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CARLOS_POSSE", &"CREDIT_H2_MATTHEW_EVANS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CARLY_SMITH", &"CREDIT_H2_MATTHEW_FEAR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CAROLINE_MCNIEL", &"CREDIT_H2_MATTHEW_HARTWELL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CAROLYN_WANG", &"CREDIT_H2_MATTHEW_HENSCHE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CASEY_KWOCK", &"CREDIT_H2_MATTHEW_KOLODZIEJCZYK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CASEY_LEE", &"CREDIT_H2_MAXWELL_BARR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CASSIDY_STEVENS", &"CREDIT_H2_MEGAN_GARRETT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CATHERINE_BYGRAVE", &"CREDIT_H2_MEGAN_PIERCE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHAD_SCHMIDT", &"CREDIT_H2_MELANIE_FARTHING" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHANDLER_ZINKE", &"CREDIT_H2_MICHAEL_AYOOB" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHANDRA_LATHANGUE", &"CREDIT_H2_MICHAEL_CONSTANTAS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHARLES_GAGNE_COTE", &"CREDIT_H2_MICHAEL_COOK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHARLES_VINSON", &"CREDIT_H2_MICHAEL_CORNFIELD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHARLIE_MURPHY", &"CREDIT_H2_MICHAEL_DIXON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHARLTON_MASON", &"CREDIT_H2_MICHAEL_GABRIEL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHASE_BROWN", &"CREDIT_H2_MICHAEL_HALL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHASE_WRENN", &"CREDIT_H2_MICHAEL_HUNAU" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHETAN_DESAI", &"CREDIT_H2_MICHAEL_JANTZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHETAN_VARMA", &"CREDIT_H2_MICHAEL_MELCHIOR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHI_LIU", &"CREDIT_H2_MICHAEL_REX" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHLOE_DE_MESA", &"CREDIT_H2_MICHAEL_ROBINSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_ARENDS", &"CREDIT_H2_MICHAEL_VASQUEZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_BAGGIO", &"CREDIT_H2_MICHAEL_WARE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_BRUENS", &"CREDIT_H2_MICHELE_IORIO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_CARTWRIGHT", &"CREDIT_H2_MIGUEL_NARANJO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_CHOWDHURY", &"CREDIT_H2_MIKE_FREEDMAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_MILLER", &"CREDIT_H2_MIKE_GONZALES" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_SCAGLIONE", &"CREDIT_H2_MIKE_MANTARRO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_SCHNAKENBERG", &"CREDIT_H2_MIKE_MORITZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_SMITH", &"CREDIT_H2_MIKE_PATTERSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_TEE", &"CREDIT_H2_MIKE_SANDERS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_TOMLINSON", &"CREDIT_H2_MIKEY_VEGA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_WALTHER", &"CREDIT_H2_MILES_WINZELER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_WILSON", &"CREDIT_H2_MINGLI_KAO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRISTER_ERICSON", &"CREDIT_H2_MISTY_NOOR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRISTIAN_ALLEN", &"CREDIT_H2_MITCH_JACOBS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRISTIAN_AVILA", &"CREDIT_H2_MITCHELL_MORITZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRISTIAN_BLENDL", &"CREDIT_H2_MOLLY_HINCHEY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRISTOPHE_COLLANGE", &"CREDIT_H2_MONICA_GARCIA_DE_LUCAS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRISTOPHER_ELLIS", &"CREDIT_H2_MONTE_LUTZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRISTOPHER_TAYLOR", &"CREDIT_H2_MORGAN_KIRKPATRICK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRISTOPHER_TEE", &"CREDIT_H2_MYO_KYAWSWAR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRISTOPHER_TEMPLETON", &"CREDIT_H2_NAKIA_HAMMOND" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRISTOPHER_WILSON", &"CREDIT_H2_NARENDRA_SABNIS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CJ_PACE", &"CREDIT_H2_NATE_CHOWN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CLAUDIA_OKADA", &"CREDIT_H2_NATE_TYLEY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CLINT_ACKERMAN", &"CREDIT_H2_NATHAN_CONSTANTINESCU" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CLIVINS_DANTUS", &"CREDIT_H2_NEIL_HOLMES" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CODDY_JOHNSON", &"CREDIT_H2_NEIL_YANG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CODY_CORONA", &"CREDIT_H2_NEVEN_DRAVINSKI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CODY_RINEHART", &"CREDIT_H2_NICHOLAS_ALBRECHT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_COLIN_KAWAKAMI", &"CREDIT_H2_NICHOLAS_BLANCHARD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_COLIN_SCHILLER", &"CREDIT_H2_NICHOLAS_INGERSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CONNOR_GERDES", &"CREDIT_H2_NICK_CLARK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CONNOR_SINGLETARY", &"CREDIT_H2_NICK_FALCO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CORY_MULLEN", &"CREDIT_H2_NICK_HARLAND" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_COURTNEY_BONSALL", &"CREDIT_H2_NICK_IGNACIO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CRAIG_WHITE", &"CREDIT_H2_NICK_LAMIA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CRECEN_CARR", &"CREDIT_H2_NICK_MATSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CYNTHIA_LAUGHLIN", &"CREDIT_H2_NICK_WAIZMAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAEKEUN_YOUN", &"CREDIT_H2_NICOLAS_ECHEVERRIA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAI_LIU", &"CREDIT_H2_NILTON_SOARES" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAMIEN_PONCEL", &"CREDIT_H2_NOAH_SARID" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAN_CHIAPPINI", &"CREDIT_H2_NOAH_THOMPSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAN_VO", &"CREDIT_H2_NOEL_FELICIANO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAN_WRIGHT", &"CREDIT_H2_NORIYUKI_DOCHI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DANIEL_ANGERS", &"CREDIT_H2_OKE_MUELLER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DANIEL_CUENDECARRERA", &"CREDIT_H2_OLESIA_BEREZENSKA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DANIEL_FLORES", &"CREDIT_H2_OLIVER_COOK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DANIEL_GREEN", &"CREDIT_H2_OLIVER_HSIA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DANIEL_PAK", &"CREDIT_H2_OMAR_GUTIERREZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DANIEL_SMITH", &"CREDIT_H2_OMER_SALIK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DANIEL_SUAREZ", &"CREDIT_H2_OSCAR_PIZANO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DANIEL_VIROCHSIRI", &"CREDIT_H2_OUSSAMA_AKIKI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DANIEL_SUAREZ", &"CREDIT_H2_OVUNC_MERT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DANIELLE_DEWALD", &"CREDIT_H2_OWEN_LANCASTER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DARRELL_GALLAGHER", &"CREDIT_H2_OZ_DE_LEONSULECIO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVE_STOHL", &"CREDIT_H2_PAOLA_PALERMO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_ALCAIDE", &"CREDIT_H2_PAPU_HASSAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_BLASER", &"CREDIT_H2_PAT_DWYER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_BLOODWORTH", &"CREDIT_H2_PAT_GERLEMAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_BULLAT_II", &"CREDIT_H2_PATRICK_ELIFELD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_CUSHMAN", &"CREDIT_H2_PATRICK_FRIEDRICH" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_DELANTY", &"CREDIT_H2_PATRICK_KELLY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_DUONG", &"CREDIT_H2_PAUL_COLBERT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_FONG", &"CREDIT_H2_PAUL_PARKER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_HODGSON", &"CREDIT_H2_PAUL_RHODES" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_JOHNSON", &"CREDIT_H2_PAUL_VIRGIN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_KILLEN", &"CREDIT_H2_PAULIINA_TORNQVUIST" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_LIM", &"CREDIT_H2_PAVEL_URUSOV" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_MESSINGER", &"CREDIT_H2_PEDRO_AGUILAR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_NEAL", &"CREDIT_H2_PELLE_SJOENELL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_SHOCHAT", &"CREDIT_H2_PERCY_PINEDA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_TYLER", &"CREDIT_H2_PERNILLA_AHGREN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAWN_ARDUINIWATSON", &"CREDIT_H2_PETE_ROYEA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DEAN_DING", &"CREDIT_H2_PETER_DAY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DELMI_SEBASTIAN", &"CREDIT_H2_PETER_NELSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DELPHINE_CALSADA", &"CREDIT_H2_PETER_ROYEA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DENNIS_DURKIN", &"CREDIT_H2_PHARABA_HACKERWITT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DEREK_BROWN", &"CREDIT_H2_PHIL_TERZIAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DESMOND_WHITE", &"CREDIT_H2_PHILIP_EARL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DIANA_DILLER", &"CREDIT_H2_PHILLIP_LAW" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DIANE_DE_DOMECY", &"CREDIT_H2_PRATEEK_JAIN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DINO_VERANO", &"CREDIT_H2_PRIDE_ST_CLAIR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DION_JACKSON", &"CREDIT_H2_PRITI_AGRAWAL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DOMINIC_CAREY", &"CREDIT_H2_QUANG_TRAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DOMINIC_KIRKWOOD", &"CREDIT_H2_QUINN_FLUMERFELT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DOMINIK_MERKUN", &"CREDIT_H2_QUINN_PENDELTON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DONOVAN_BYRNES", &"CREDIT_H2_RACHAEL_GRANT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DOROTHY_TONG", &"CREDIT_H2_RACHEL_OVERTON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DOUG_OWEN", &"CREDIT_H2_RAHUL_AGARWAL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DOUGLAS_TAFOYA", &"CREDIT_H2_RAHUL_PRASAD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DOV_CARSON", &"CREDIT_H2_RAMAKRISHNA_DEVINENI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DREW_ELLIOT", &"CREDIT_H2_RAMBABU_DAMA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DREW_LYONS", &"CREDIT_H2_RANA_BRAHMA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DREW_MILLER", &"CREDIT_H2_RANDY_DE_RAMA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DREW_OLSEN", &"CREDIT_H2_RAVEN_CRUZFADDEN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DUPREE_DAWSON", &"CREDIT_H2_RAY_DORSCHNER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DUSTIN_CARTER", &"CREDIT_H2_RAY_MCMASTER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DUSTIN_LOUDON", &"CREDIT_H2_RAYMOND_MASSA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ED_JUN", &"CREDIT_H2_REBECCA_CZAICKA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EDDIE_CHAN", &"CREDIT_H2_REI_LIOU" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EDDIE_GUTIERREZ", &"CREDIT_H2_RENITA_MCBRIDE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EDGAR_GUTIERREZ", &"CREDIT_H2_RICH_LISHEWSKI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EDUARDO_GUTIERREZ", &"CREDIT_H2_RICHARD_SNYDER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EDWARD_VERNON", &"CREDIT_H2_RICHARD_TOM" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EJ_ALCANTARA", &"CREDIT_H2_RICK_BETSCH" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ELANY_TORRES", &"CREDIT_H2_RICK_PEREZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ELENA_ABELLA", &"CREDIT_H2_RICK_SLOOF" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ELIJAH_MARTINS", &"CREDIT_H2_ROB_KOSTICH" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ELLE_OBRIEN", &"CREDIT_H2_ROB_SCHONFELD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EMERY_THOMPSON", &"CREDIT_H2_ROBBY_MYERS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EMILY_GOEUN_KIM", &"CREDIT_H2_ROBERT_KIKABHAI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EMILY_WOOLLISCROFT", &"CREDIT_H2_ROBERT_KOSTICH" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EMMA_SUNGEUN_KIM", &"CREDIT_H2_ROBERT_MALDONADO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ENRICO_BONGO", &"CREDIT_H2_ROBERT_ORR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ERENIS_LEMUS", &"CREDIT_H2_ROBERT_TAYLOR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ERIC_HIRSHBERG", &"CREDIT_H2_ROBERT_WHARTON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ERIC_SUMIDA", &"CREDIT_H2_ROBERTO_NABOR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ERIC_WHANG", &"CREDIT_H2_ROBIN_PETEL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ESTEBAN_BARTEN", &"CREDIT_H2_RODRIGO_PEREZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ESTEVAN_CERVANTES", &"CREDIT_H2_RODRIGO_PEREZ2" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ETHAN_KING", &"CREDIT_H2_ROMALLIS_TUCKER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EUGENE_WU", &"CREDIT_H2_ROMAN_FRANCE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EUNICE_LEE", &"CREDIT_H2_RONALD_JOSHUA_SAMUEL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EVA_LARA", &"CREDIT_H2_RONNIE_LOU" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EVALINA_SHIN", &"CREDIT_H2_RORY_HUDDLESTON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EVAN_BING", &"CREDIT_H2_ROXANA_DEVORE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EVAN_BUTTON", &"CREDIT_H2_RUBEN_DEHOUCK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EVAN_THOMAS", &"CREDIT_H2_RUSS_MELANSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EVAN_WINGREN", &"CREDIT_H2_RUTH_BERENJI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FAIZA_NELSON", &"CREDIT_H2_RYAN_ANDERSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FEBISOLA_OMATSONE", &"CREDIT_H2_RYAN_BACKSTROM" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FELICITY_TREVINO", &"CREDIT_H2_RYAN_FORD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FELIPE_MAGALLON", &"CREDIT_H2_SABRINA_VELOSO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FERGUS_LINDSAY", &"CREDIT_H2_SALAH_KHALIL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FIONA_EBBS", &"CREDIT_H2_SALOME_VILLARRUEL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FLORDELIZ_MARY_FOLSE", &"CREDIT_H2_SAM_COOPER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FRANCES_JENSEN", &"CREDIT_H2_SAM_FOWLER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FRANCES_ONEILL", &"CREDIT_H2_SAM_SILVERMAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FRANCESCO_CORONA", &"CREDIT_H2_SAM_WINOTAI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FRANCIS_JAMES_JIMENEZ", &"CREDIT_H2_SAM_YUN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FRANCISCO_BERUMEN", &"CREDIT_H2_SAMANTHA_STAUFFER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FRANCK_MORISSEAU", &"CREDIT_H2_SAMI_ELTAIB" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FRANK_NUNES", &"CREDIT_H2_SANDEEP_HEGDE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FREDERIC_EMERY", &"CREDIT_H2_SANDEEPKUMAR_AMRUTIA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FREDERICK_WARBURTON", &"CREDIT_H2_SANG_KIM" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GABE_ALONSO", &"CREDIT_H2_SANJIT_PATEL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GABRIELA_VENTURINI", &"CREDIT_H2_SARA_SCHILLERSTROM" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GARETH_DAVIES", &"CREDIT_H2_SARAH_PAVLINA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GARRETT_BRODIE", &"CREDIT_H2_SATYANARAYANA_MUTHYALA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GEOFF_BENT", &"CREDIT_H2_SCOTT_KRAGER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GEORGE_KIM", &"CREDIT_H2_SCOTT_MACFARLANE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GHASSAN_BURHAN", &"CREDIT_H2_SCOTT_MAGIE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GIACOMO_CASAROTTO", &"CREDIT_H2_SCOTT_MURATA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GIFTY_NTIAMOAH", &"CREDIT_H2_SCOTT_TOBIAS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GLENN_VISTANTE", &"CREDIT_H2_SEAN_CARGLE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GOPI_KRISHNA_PONNAM", &"CREDIT_H2_SEAN_DARTER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GORDON_KAICHIEH_LO", &"CREDIT_H2_SEAN_DEXHEIMER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GRACE_MOLINA", &"CREDIT_H2_SEAN_JUNKINS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GREG_DZHALALYANTS", &"CREDIT_H2_SEAN_MOYLAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GREGORY_BERTILSON", &"CREDIT_H2_SEAN_SKINNER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GUNNER_LEE", &"CREDIT_H2_SEAN_WILLIAMS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GUS_KNESS", &"CREDIT_H2_SERBAN_PETRE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GUSTAVO_ALVARADO", &"CREDIT_H2_SERGEI_ACUNA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GUY_PERKINS", &"CREDIT_H2_SHANE_NEEDHAM" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HAMED_BERENJI", &"CREDIT_H2_SHANMUKHA_SVB_BONDA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HAO_QI", &"CREDIT_H2_SHANNON_GALLOWAY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HARIKA_AVULA", &"CREDIT_H2_SHAUNA_RUTHENBECK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HARIKRISHNAN_NAMBIAR", &"CREDIT_H2_SHAWN_BELEW" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HARIKRISHNAN_THAZHATHVEETIL", &"CREDIT_H2_SHAWN_FEENEY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HARINI_VENKATESH", &"CREDIT_H2_SHAYNE_STERLING" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HARRY_BOUNDEN", &"CREDIT_H2_SHIN_OGAWA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HEATHER_POLUBINSKI", &"CREDIT_H2_SHO_YORIMOTO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HEATHER_WISE", &"CREDIT_H2_SHRUTI_PARMAR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HELEN_HOPPER", &"CREDIT_H2_SIAN_CLARKE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HENRY_ZURAWSKI", &"CREDIT_H2_SIDDHARTHA_DEWAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HILARY_PERCHARD", &"CREDIT_H2_SIMON_WOLFE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HOJEONG_KIM", &"CREDIT_H2_SIRI_JANSSON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HUGH_TIETZE", &"CREDIT_H2_SOLOMON_LAMBERT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_IAN_JAMES", &"CREDIT_H2_SOUMEN_SARKAR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_IAN_TROMBETTA", &"CREDIT_H2_SPENCE_NEUMANN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_IGNACIO_AVILA", &"CREDIT_H2_SPENCER_KING" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_INDRA_YEE", &"CREDIT_H2_SRIHARI_SADAGOPARAMANUJAM" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_INDYA_JOHNSON", &"CREDIT_H2_SRINIVAS_REDDI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ISAAC_LUEDTKE", &"CREDIT_H2_STEFFANY_POWELL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_IVORY_JONES", &"CREDIT_H2_STEPHANIE_DEMING__XLOC_INC" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_J_EATEDALI", &"CREDIT_H2_STEPHANIE_GLOVER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JACK_BURROWS", &"CREDIT_H2_STEPHEN_IMAMURA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JACK_JAMES_KLECKNER", &"CREDIT_H2_STEPHEN_MARKS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JACK_KLECKNER", &"CREDIT_H2_STEPHEN_SEUNG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JACKIE_LIU", &"CREDIT_H2_STEVE_ISOM" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JACKY_CHAN", &"CREDIT_H2_STEVE_YOUNG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JACOB_JOHNSON", &"CREDIT_H2_STEVEN_MENDOZA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAEYOUNG_CHOI", &"CREDIT_H2_SUNG_YOO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAKE_WHISLER", &"CREDIT_H2_SUNGJIN_KIM" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAMES_BONTI", &"CREDIT_H2_SUNIL_KUMAR_BALUSU" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAMES_CABELNEIL", &"CREDIT_H2_SUNNY_ARORA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAMES_HENNESSEY", &"CREDIT_H2_SUNPREET_BANGAR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAMES_HOULTON", &"CREDIT_H2_SURIYA_PRAKASH_KARUPPAIYAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAMES_LODATO", &"CREDIT_H2_SVEN_POHLE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAMES_MATTONE", &"CREDIT_H2_SWATHI_YERAGUDIPATI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAMES_NICKERSON", &"CREDIT_H2_TANYA_BERG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAMES_OH", &"CREDIT_H2_TARYN_HUTT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAMIE_VENABLE", &"CREDIT_H2_TEDDY_HWANG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAMISON_HUBER", &"CREDIT_H2_TEGAN_KNIGHT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JANA_JIANG", &"CREDIT_H2_TERRI_DURHAM" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JANICE_FRIEDEN", &"CREDIT_H2_TERRY_KIEL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JARED_CASTLE", &"CREDIT_H2_THIAGO_ONORATO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JARED_KLEBER", &"CREDIT_H2_THOMAS_MERCIER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JASMINE_ALLEN", &"CREDIT_H2_THOMAS_TIPPL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JASON_ADES", &"CREDIT_H2_THOMAS_VAIL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JASON_LEIGH", &"CREDIT_H2_TIM_LION" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JASON_LEMBCKE", &"CREDIT_H2_TIM_RONDEAU" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAVONNE_WALKER", &"CREDIT_H2_TIMOTHY_ELLIS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAY_PLANTE", &"CREDIT_H2_TODD_HARVEY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEFF_BROWN", &"CREDIT_H2_TODD_KONG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEFF_PARKER", &"CREDIT_H2_TODD_MUELLER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEFF_ROPER", &"CREDIT_H2_TODD_PRUYN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEFF_TAYLOR", &"CREDIT_H2_TODD_SZALLA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEFF_WARD", &"CREDIT_H2_TOM_ESTES" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEFFREY_BORDER", &"CREDIT_H2_TOM_FLYNN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEFFREY_OTTAWAY", &"CREDIT_H2_TOM_NEAL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEFFREY_TAYLOR", &"CREDIT_H2_TOM_READ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEN_CODRINGTON", &"CREDIT_H2_TOM_VAIL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEN_KALINOWSKI", &"CREDIT_H2_TOMASZ_WOJTKIEWICZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEN_MIRABELLI", &"CREDIT_H2_TONY_NIXON" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEN_SULLIVAN", &"CREDIT_H2_TRACY_SCHAPIRA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JENE_CRANDALL", &"CREDIT_H2_TRAVIS_MURRAY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JENNI_VO", &"CREDIT_H2_TRAVIS_STANSBURY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JENNIFER_FRIED", &"CREDIT_H2_TREVOR_BRESAW" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JENNIFER_HUR", &"CREDIT_H2_TYLER_MICHAUD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JENNIFER_KALINOWSKI", &"CREDIT_H2_TYLER_PHILLIPPI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEREMY_ANDERSON", &"CREDIT_H2_TYLER_VILLALOBOS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEREMY_LEVI", &"CREDIT_H2_VENKATA_SATYANARAYANA_RAJU_MANTENA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JEREMY_THOMPSON", &"CREDIT_H2_VICKY_LE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JERRET_PATRICK", &"CREDIT_H2_VICTOR_GUERRERO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JESSE_WANG", &"CREDIT_H2_VICTOR_LOGAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JESSICA_PORTER", &"CREDIT_H2_VICTOR_LOPEZ" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JESSICA_WHEELER", &"CREDIT_H2_VICTORIA_FISHER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JESUS_ROSALES", &"CREDIT_H2_VICTORIA_HARKINS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JIAN_WANG", &"CREDIT_H2_VIDAR_NILSEN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JIEUN_RYU", &"CREDIT_H2_VIJAYENDRA_BODA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JIM_MCMULLIN", &"CREDIT_H2_VINCENT_COUCH" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JIYE_ELLIE_LEE", &"CREDIT_H2_VINCENT_HIGGINS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOANNA_CHEN", &"CREDIT_H2_VINCENT_VESPA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOE_BRUNA", &"CREDIT_H2_VINDHYA_ANNE_SHIVAKUMAR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOE_CAMMORATA", &"CREDIT_H2_VINOBA_KUMAR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOE_KAM", &"CREDIT_H2_VIRGINIA_VEGA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOE_MANLY", &"CREDIT_H2_WILL_CRANMER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOEY_COUCH", &"CREDIT_H2_WILLIAM_HOWARD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOEY_DERRICO", &"CREDIT_H2_WILLIAM_SHEPARD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOEY_SMITS", &"CREDIT_H2_XIANCHUN_WU" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOHN_BAKER", &"CREDIT_H2_XIAOMING_WU" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOHN_BLACKBURN", &"CREDIT_H2_YANBING_CHEN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOHN_BROOKS", &"CREDIT_H2_YING_HSUAN_HUNG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOHN_GORDON", &"CREDIT_H2_YIP_NGOK_LAM_INDY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOHN_PARISH", &"CREDIT_H2_YOKO_OTA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOHN_PURDHAM", &"CREDIT_H2_YONGWON_LA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOHNNY_KIM", &"CREDIT_H2_YONGYI_ZHU" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JON_BUTCHER", &"CREDIT_H2_ZACH_DRISCOLL" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JON_ESTANISLAO", &"CREDIT_H2_ZACH_HAYES" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JON_PAUL_HART", &"CREDIT_H2_ZACHARY_MORAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JONATHAN_BUTCHER", &"CREDIT_H2_ZACHERY_HUMPHREYS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JONATHAN_FARGHER", &"CREDIT_H2_ZOE_PUSATERI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JONATHAN_GOMEZ", "" );
    maps\_credits::addgap();
    maps\_credits::addcenterheading( &"CREDIT_H2_EXTERNAL_PARTNERS" );
    maps\_credits::addgap();
    maps\_credits::addgap();
}

initatvicredits_artbully()
{
    maps\_credits::addcenterimage( "LOGO_ARTBULLY", 256, 128, 4.375 );
    maps\_credits::addgap();
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEKSANDAR_FODOR", &"CREDIT_H2_LJUBOMIR_RUSKAJI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANA_BOGDANOVIC", &"CREDIT_H2_MARCUS_DUBLIN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AUGUSTIN_LUCA", &"CREDIT_H2_MARKO_KOVACEVIC" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AXEL_KRAEFFT", &"CREDIT_H2_MILOS_SAVKOVIC" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BOSKO_VASOVIC", &"CREDIT_H2_NATASA_STAMENKOVIC" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_STEFANOVIC", &"CREDIT_H2_NIKOLA_PETROVIC" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ELVIS_POSA", &"CREDIT_H2_PAUL_BOUTROS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GAURAV_SHARMA", &"CREDIT_H2_SANKET_GUPTA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_IVAN_JANKOVIC", &"CREDIT_H2_THIAGO_SOUZA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_IVAN_RISTIC", &"CREDIT_H2_VIKTOR_POPOVIC" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JACOB_ATIENZA", &"CREDIT_H2_VLADISLAV_CVIJOVIC" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JASVINDER_SINGH", &"CREDIT_H2_YOGESH_SHARMA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_KALEB_AYLSWORTH", &"CREDIT_H2_ZELJKO_TASIC" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_LALIT_SHRIVASTAVA", &"CREDIT_H2_ZORAN_RATIC" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_LAZAR_SVRKOTA", "" );
    maps\_credits::addgap();
}

initatvicredits_elite()
{
    maps\_credits::addcenterimage( "LOGO_ELITE3D", 256, 128, 4.375 );
    maps\_credits::addgap();
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ADRIAN_TORRES", &"CREDIT_H2_JUSTIN_GREEN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALBERTO_CEBRIAN", &"CREDIT_H2_KIERAN_DUBERY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEX_JARENO", &"CREDIT_H2_MANUEL_DORADO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALVARO_SAN_JUAN", &"CREDIT_H2_MARTIN_VATER" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANGEL_BLANCO", &"CREDIT_H2_MATHIJS_KAPTEIJN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANTONIO_FIGUEIREDO", &"CREDIT_H2_MATTEO_MINGOZZI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANTONIO_PONS", &"CREDIT_H2_MIGUEL_MOURAO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BART_DE_VRIES", &"CREDIT_H2_MIGUEL_VARELA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BJORN_SEINSTRA", &"CREDIT_H2_MONIQUE_VAN_BUITENEN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHRIS_WATTS", &"CREDIT_H2_NACHO_LAPUENTE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DACHI_GOG", &"CREDIT_H2_NAJIM_FILALI_SAKSAK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAVID_CHUMILLA", &"CREDIT_H2_NATALIA_GALANTSEVA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DENIMIRA_DENEVA", &"CREDIT_H2_NICOLAS_REPETTO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DONNIE_OLIVER", &"CREDIT_H2_OSCAR_FERRERO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EDGAR_TUDELA", &"CREDIT_H2_PATRICIO_GARNICA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FELIX_VAN_DEN_BERG", &"CREDIT_H2_PAU_ROVIRA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FERNANDO_MORAL", &"CREDIT_H2_REZA_AFSHAR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FREDERIK_OSTYN", &"CREDIT_H2_ROSA_VAN_WOUWE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HECTOR_TERUEL", &"CREDIT_H2_RUBEN_AREMA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAVIER_SANCHEZ", &"CREDIT_H2_RUBEN_SIGNES" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JESUS_MERINO", &"CREDIT_H2_SERGE_KARPOVS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOERI_VROMMAN", &"CREDIT_H2_TIM_PAAUWE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JORGE_BARROS", &"CREDIT_H2_TIMUR_GRAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JOSE_LUIS_QUERAL", &"CREDIT_H2_VALERIO_DE_CAROLIS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JULIAN_CAMPILLO", &"CREDIT_H2_VICTOR_MERKULOV" );
    maps\_credits::addgap();
}

initatvicredits_redhot()
{
    maps\_credits::addcenterimage( "LOGO_REDHOT", 256, 128, 4.375 );
    maps\_credits::addgap();
    maps\_credits::addcenternamedouble( &"CREDIT_H2_AMIRUL_HAQ_HUSNUL_FADLI", &"CREDIT_H2_PERBOWO_WICAKSONO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ASIEF_AKBAR_WIRAWAN", &"CREDIT_H2_RANGGA_MALIK_RAJASHA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_BAGUS_GALIH_SATRIA", &"CREDIT_H2_RUDI_INDRA_ADITIA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CAI_JIANYONG", &"CREDIT_H2_SANDY_ZHANG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_CHETAN_KOTI", &"CREDIT_H2_SCOTT_ZHAO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DAN_LIXIANG", &"CREDIT_H2_SONG_ZIJIAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DANIEL_STATON", &"CREDIT_H2_SUN_YUNQI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DUAN_ZIYU", &"CREDIT_H2_TANG_SHAOMIN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GAYUS_HENDRIANTO", &"CREDIT_H2_WANG_CHUNYUN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GUO_YUANBO", &"CREDIT_H2_WANG_GONGLIANG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_GUO_ZHEN", &"CREDIT_H2_WANG_QICHAO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HARNINDYO_INUBHIMANTORO", &"CREDIT_H2_WANG_SHUAI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HUANG_XIAOYANG", &"CREDIT_H2_WANG_TAO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JAMAL_JAMES", &"CREDIT_H2_WANG_ZHE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JI_XIAOCHEN", &"CREDIT_H2_WEI_WEIBEN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_KUAI_LEILEI", &"CREDIT_H2_WU_CHENGDONG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_LEO_LING", &"CREDIT_H2_XIONG_QIJUN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_LI_CHENGCHENG", &"CREDIT_H2_YANG_HELI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_LI_PENG", &"CREDIT_H2_YOSI_SAPUTRA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_LI_SHAOQUAN", &"CREDIT_H2_YU_FANGLIN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_LI_YINGYING", &"CREDIT_H2_ZHANG_SHUFEI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_LIU_GUANYU", &"CREDIT_H2_ZHANG_YONG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_LIU_HAOQING", &"CREDIT_H2_ZHANG_YUAN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_LIU_QINZI", &"CREDIT_H2_ZHAO_GUANYU" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_LIU_SHUOMENG", &"CREDIT_H2_ZHU_TENGFEI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_LUO_RUNHENG", &"CREDIT_H2_ZHU_YINHUA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_MOHAMMAD_ISMAIL", "" );
    maps\_credits::addgap();
}

initatvicredits_ringtail()
{
    maps\_credits::addcenterimage( "LOGO_RINGTAIL", 256, 128, 4.375 );
    maps\_credits::addgap();
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANASTASIA_KUNAKOVA", &"CREDIT_H2_MAKSIM_BALAHNITSOV" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDREI_KRUGLOV", &"CREDIT_H2_MARK_VOROBJOV" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDREI_VOLOSHIN", &"CREDIT_H2_NAOMI_UNT" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANTON_ALEKNAVITSJUS", &"CREDIT_H2_OLEG_TSURIKOV" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANTON_ILJIN", &"CREDIT_H2_OLESJA_MALEI" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANTON_SEREDA", &"CREDIT_H2_PAVEL_ARNOLD" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DENNIS_RAZUMOV", &"CREDIT_H2_RAUNO_KIVIBERG" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_EVGENI_SUDAK", &"CREDIT_H2_RIMMA_ROMANETS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_FREDI_TARENOMM", &"CREDIT_H2_ROMAN_GUNENKOV" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_IOANNIS_KORNARAKIS", &"CREDIT_H2_SERGEI_KIRILLOV" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JURI_ALBREHT", &"CREDIT_H2_SERGEI_VARASK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JURI_UNT", &"CREDIT_H2_TOOMAS_LAIK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_KIRILL_RYBKO", &"CREDIT_H2_TOOMAS_TARO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_KRISTINA_MILLER", &"CREDIT_H2_VLADIMIR_TOOTSI" );
    maps\_credits::addgap();
}

initatvicredits_ssup()
{
    maps\_credits::addcenterimage( "LOGO_SSUP", 256, 128, 4.375 );
    maps\_credits::addgap();
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANTOINE_BERUBE", &"CREDIT_H2_MATHIEU_BLOUIN" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_HUBERT_VALLEE", &"CREDIT_H2_PIERRELUC_BERUBE" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_JUDYANN_BUSSIERES", &"CREDIT_H2_THOMAS_GIROUX" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_LOUISETIENNE_BEAUPRE", "" );
    maps\_credits::addgap();
}

initatvicredits_ulysse()
{
    maps\_credits::addcenterimage( "LOGO_ULYSSES", 256, 128, 4.375 );
    maps\_credits::addgap();
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXANDR_KACHANUK", &"CREDIT_H2_MAXIM_MANUYLOV" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXANDR_KHALIMAN", &"CREDIT_H2_MAXIM_SAVKOV" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXANDR_LINOVICHENKO", &"CREDIT_H2_OLGA_TROKHYMOVYCH" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALEXANDR_MATVIYCHUK", &"CREDIT_H2_SERGEI_CHEBOTOK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ALINA_SUKACH", &"CREDIT_H2_SERGEI_KOTENKO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANATOLIY_CHECHEL", &"CREDIT_H2_SERGEY_MAZUR" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDREY_PERSHUTA", &"CREDIT_H2_SERGEY_SPASCHENKO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDRII_CHEREPIN", &"CREDIT_H2_TARAS_MALYARENKO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANDRII_MIKHAILOV", &"CREDIT_H2_VLADIMIR_KALACHOV" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_ANTON_KULYNYCH", &"CREDIT_H2_VLADIMIR_STEPANIYK" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DENYS_BULAKH", &"CREDIT_H2_VLADYSLAV_HLUSHKO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_DIANA_TARNAVSKA", &"CREDIT_H2_YAROSLAV_ZELENSKY" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_IGOR_SIDORENKO", &"CREDIT_H2_YEKATERINA_ZAIKINA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_IRYNA_KACHKALDA", &"CREDIT_H2_YURI_KLYMENKO" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_IVAN_KENC", &"CREDIT_H2_YURI_KOMPANEYETS" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_KIRILL_ILIN", &"CREDIT_H2_YURIY_NERETA" );
    maps\_credits::addcenternamedouble( &"CREDIT_H2_KIRILL_UDODOV", "" );
    maps\_credits::addgap();
    maps\_credits::addcenterheading( &"CREDIT_H2_MUSIC" );
    maps\_credits::addgap();
    maps\_credits::addcentertriple( "", &"CREDIT_H2_UNTIL_THE_DAY_I_DIE", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_WRITTEN__PERFORMED_BY_DAN_SKINNER_ADAM_SKINNER_AND_RANDALL_BRENEMAN", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_PROVIDED_BY_AUDIO_NETWORK_US_INC", "" );
    maps\_credits::addspace();
    maps\_credits::addcentertriple( "", &"CREDIT_H2_TOO_MUCH", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_COMPOSED_BY_RICHARD_MYHILL", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_PUBLISHED_BY_APM_MUSIC_KPM", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_COURTESY_OF_APM_MUSIC", "" );
    maps\_credits::addspace();
    maps\_credits::addcentertriple( "", &"CREDIT_H2_SURVIVAL_SKILLS", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_KRSONE__BUCKSHOT", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_R_IBANGA_JR_K_BLAKE_L_PARKER", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_DA_SOUR_MILK_CAFE_PUBLISHING_ASCAP__TARGET_PRACTICE_GROUP_MUSIC_ASCAP", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_BDP_MUSIC_ZOMBA_MUSICUNIVERSAL_MUSIC_GROUP", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_DUCK_DOWN_MUSIC_INC_2009", "" );
    maps\_credits::addspace();
    maps\_credits::addcentertriple( "", &"CREDIT_H2_DANGER", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_MARCO_POLO__TORAE", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_T_CARR_M_BRUNO", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_CONEY_ISLANDS_FINEST_ASCAP_M_BRUNO_SOCANSESAC", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_DUCK_DOWN_MUSIC_INC_2009", "" );
    maps\_credits::addspace();
    maps\_credits::addcentertriple( "", &"CREDIT_H2_NEW_NEW", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_SUGA_CITY_FT_MARIA_V", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_ARKANSAS_BO_MARLON_JENNINGS_AND_GOINES_ANDREW_GOINS", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_CONDUIT_PUBLISHING", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_LABEL_COURTESY_CREDIT_CONDUIT_ENTERTAINMENT", "" );
    maps\_credits::addspace();
    maps\_credits::addcentertriple( "", &"CREDIT_H2_THE_DEATH_OF_ULYSSES", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_COMPOSED_BY_ERIC_CAISSY", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_PUBLISHED_BY_APM_MUSIC_CEZAME_METRO_PARK", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_COURTESY_OF_APM_MUSIC", "" );
    maps\_credits::addspace();
    maps\_credits::addcentertriple( "", &"CREDIT_H2_COSSACK_DANCE", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_COMPOSED_BY_ROBERT_FOSTER", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_PUBLISHED_BY_APM_MUSIC_KPM", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_COURTESY_OF_APM_MUSIC", "" );
    maps\_credits::addspace();
    maps\_credits::addcentertriple( "", &"CREDIT_H2_BAHIA", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_WRITTEN__PERFORMED_BY_CAMPBELL_E_BROWNING_GUILHERME_LOPES_RODRIGUES", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_JAIR_CLAUDINO_RODRIGUES_JUNIOR_PABLO_LOVE", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_PROVIDED_BY_AUDIO_NETWORK_US_INC", "" );
    maps\_credits::addspace();
    maps\_credits::addcentertriple( "", &"CREDIT_H2_KALASHNIKOV", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_COMPOSED_MIXED__MASTERED_BY_NICK_TREMBLAY", "" );
    maps\_credits::addspace();
    maps\_credits::addcentertriple( "", &"CREDIT_H2_BRUTAL_ENDING", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_COMPOSED_MIXED__MASTERED_BY_NICK_TREMBLAY", "" );
    maps\_credits::addgap();
    maps\_credits::addcenterheading( &"CREDIT_H2_ADDITIONAL_SERVICES" );
    maps\_credits::addgap();
    maps\_credits::addcentertriple( "", &"CREDIT_H2_PETROL", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_THE_CHARACTERS_AND_EVENTS_DEPICTED_IN_THIS_GAME_ARE_FICTICIOUS", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_ANY_SIMILARITY_TO_ACTUAL_PERSONS_LIVING_OR_DEAD_IS_PURELY_COINCIDENTAL", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_LOCALISATION_TOOLS__SUPPORT", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_PROVIDED_BY_STEPHANIE_DEMING__XLOC_INC", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_FONTS_PROVIDED_BY_MONOTYPE_IMAGING_INC", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_USES_BINK_VIDEO_COPYRIGHT__19972020_RAD_GAME_TOOLS_INC", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_USES_OODLE_COPYRIGHT__20082020_BY_RAD_GAME_TOOLS_INC", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_USES_UMBRA_2006__2020_SEE_UMBRA3DCOM_FOR_DETAILS", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_STILL_IMAGES_SUPPLIED_BY_GETTY_IMAGES", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_ANIMATION_VERTIGO", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_SQUEEZE_STUDIO_ANIMATION", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_DIVISION_XP", "" );
    maps\_credits::addspace();
    maps\_credits::addcenterimage( "LOGO_HAVOK", 327, 81, 4.375 );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_CALL_OF_DUTY_MODERN_WARFARE_2_CAMPAIGN_REMASTERED_USES_HAVOK", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_COPYRIGHT_19992020_HAVOKCOM_INC_AND_ITS_LICENSORS", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_ALL_RIGHTS_RESERVED_SEE_WWWHAVOKCOM_FOR_DETAILS", "" );
    maps\_credits::addspace();
    maps\_credits::addcenterimage( "LOGO_DOLBY", 65, 85, 4.375 );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_DOLBY_DOLBY_AUDIO_AND_THE_DOUBLED_SYMBOL_ARE_TRADEMARKS_OF_DOLBY_LABORATORIES", "" );
    maps\_credits::addgap();
    maps\_credits::addcentertriple( "", &"CREDIT_H2_THE_SRTMGL_DATA_PRODUCTS_WERE_RETRIEVED_FROM_THE_ONLINE_STRM", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_COURTESY_OF_THE_NASA_EOSDIS_LAND_PROCESSES_DISTRIBUTED_ACTIVE", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_ARCHIVE_CENTER_LP_DAAC_USGSEARTH_RESOURCES_OBSERVATION", "" );
    maps\_credits::addcentertriple( "", &"CREDIT_H2_AND_SCIENCE_EROS_CENTER_SIOUX_FALLS_SOUTH_DAKOTA", "" );
    maps\_credits::addgap();
    maps\_credits::addcenterimage( "CREDITS_THANKS", 200, 50, 4.375 );
}

_id_B775()
{
    initiwcredits_iw();
    initiwcredits_beenox();
    initiwcredits_ca();
    initiwcredits_nerve();
    initiwcredits_irongalaxy();
}

initactivisioncredits()
{
    _id_C851();
    initatvicredits_artbully();
    initatvicredits_elite();
    initatvicredits_redhot();
    initatvicredits_ringtail();
    initatvicredits_ssup();
    initatvicredits_ulysse();
}
